### ISSUE TITLE
Blog post about shared appsettings

### ISSUE THREAD

**Issue by tincann** [andrewlock/blog-examples#54]
Hi Andrew,

In [this blogpost](https://andrewlock.net/sharing-appsettings-json-configuration-files-between-projects-in-asp-net-core/) you're talking about sharing appsettings accross multiple projects. 

```
.ConfigureAppConfiguration((hostingContext, config) =>
{
    var env = hostingContext.HostingEnvironment;

    var sharedFolder = Path.Combine(env.ContentRootPath, "..", "Shared");

    config
        .AddJsonFile(Path.Combine(sharedFolder, "SharedSettings.json"), optional: true) // When running using dotnet run
        .AddJsonFile("SharedSettings.json", optional: true) // When app is published
        .AddJsonFile("appsettings.json", optional: true)
        .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);

    config.AddEnvironmentVariables();
})
```

The behavior I observe when setting the `Build action` and `Copy to Output directory` properties of my SharedSettings.json file to `Content` and `Copy if newer`, respectively, is that `dotnet run` copies the SharedSettings.json to the build directory as expected. Therefore, it is not needed to specify a path (as seen below) to the relative location of SharedSettings.json. 

> .AddJsonFile(Path.Combine(sharedFolder, "SharedSettings.json"), optional: true) // When running using dotnet run

This will work for local development, as well post publish. Is this correct? Or am I missing something?

Thanks!

**Comment by tincann** [comment]
I understand now. The above is true for Console apps, but not for Web apps where the ContentRoot is not equal to the build directory. I fixed it with this:

```
        private static IConfigurationBuilder AddSharedConfig(this IConfigurationBuilder config, IHostingEnvironment env) {
            var appSettingsPath = "appsettings-shared.json";

            if(env.EnvironmentName == "Development") {
                appSettingsPath = Path.Combine(env.ContentRootPath, "..", "appsettings-shared.json");
            }

            return config.AddJsonFile(appSettingsPath, optional: false, reloadOnChange: true);
        }
```

The advantage here is that you can set `optional` to false, which will give an error if the file can't be loaded.

**Comment by andrewlock** [comment]
Yeah, you got it 🙂 if that works for you, great! I wasn't able to use it that approach, as people run environments locally in multiple ways, so can't make those assumptions based on environment🙂
