### ISSUE TITLE
404 for Sample

### ISSUE THREAD

**Issue by 274188A** [andrewlock/blog-examples#75]
Nice post on Auth0 + SS Blazor

Just a heads up the url in the post for the sample gives a 404

**Blog Post**
https://andrewlock.net/adding-authentication-to-a-blazor-server-app-using-auth0/

**404 Url**
https://github.com/andrewlock/blog-examples/tree/master/Auth0BlazorServer

PS
would love to learn some more on the [Next Steps](https://andrewlock.net/adding-authentication-to-a-blazor-server-app-using-auth0/#next-steps) - ie permissions/claims.

**Comment by andrewlock** [comment]
Oops, thanks, forgot to push, fixed it now!
