### ISSUE TITLE
debug with docker

### ISSUE THREAD

**Issue by wuzhenda** [andrewlock/blog-examples#79]
I referenced the artical [https://andrewlock.net/sharing-appsettings-json-configuration-files-between-projects-in-asp-net-core/](url)
that share appsettings.json files between projects. it works OK.
but when debug with docker ,it  told us that can't find the files,which means still need to copy the linked file to the real file location.

is there any way to fix it?
tks.

**Comment by andrewlock** [comment]
I'm afraid I don't use Debug with Docker, but it _should_ work, as long as the shared files are accessible in the docker container
