### ISSUE TITLE
Incrementality of this generator is under the question.

### ISSUE THREAD

**Issue by lsoft** [andrewlock/blog-examples#81]
Sorry for disturbing you, I noticed about this problem about a week ago and I'm not sure I understand this correctly, but looks like this generator is not incremental at all.

[Here](https://github.com/zompinc/sync-method-generator/issues/20) I read that

```
 I think I know what tutorial you probably followed here, but I'm afraid it was just completely incorrect.
...
You should never have any compilations or symbols in any steps of your incremental pipelines, and especially in output steps.
Those objects are not equatable and not meant to be used this way.
```

https://github.com/andrewlock/blog-examples/blob/b492595ec28016e88ceee6385a57a0686b77d33e/NetEscapades.EnumGenerators3/src/NetEscapades.EnumGenerators/EnumGenerator.cs#L25

If I correct it would super cool to fix this place and update your [tutorial](https://andrewlock.net/creating-a-source-generator-part-1-creating-an-incremental-source-generator/). A lot of people follow that tutorial and [obtain this error](https://github.com/search?q=IncrementalValueProvider%3C%28Compilation&type=code).

Again, I'm not sure I understand the things correctly. Sorry if I'm wrong.
Thanks!

**Comment by andrewlock** [comment]
Yikes, yeah, I wrote that series shortly after incremental generators were released, and noone really understood the requirements at the time 😬 I'm planning an updated blog post on these perf things anyway, so I'll prioritise updating those posts at the same time.

Thanks for the heads up!

**Comment by andrewlock** [comment]
FYI, I've just updated that post, and the example code in here 🙂 I would still recommend basing any generators you write off the "production" version here: https://github.com/andrewlock/NetEscapades.EnumGenerators but at least it's not so obviously broken now! 🤦‍♂️  Thanks
